builds:
  - id: "cli-proxy-api"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/server/
    binary: cli-proxy-api
archives:
  - id: "cli-proxy-api"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - README_CN.md
      - config.example.yaml