repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt (auto-fix and restage)
        entry: bash -c 'gofmt -w "$@" && git add "$@"'
        language: system
        pass_filenames: true
        types: [go]
        stages: [commit]
