port: 8317
auth-dir: "~/.cli-proxy-api"
debug: true
proxy-url: ""
quota-exceeded:
  switch-project: true
  switch-preview-model: true
api-keys:
  - "12345"
  - "23456"
generative-language-api-key:
  - "AIzaSy...01"
  - "AIzaSy...02"
  - "AIzaSy...03"
  - "AIzaSy...04"
